version: '3'

services:
  mongodb:
    image: mongo:4.1.8
    hostname: ofriends-mongodb
    ports:
      - "27017:27017"
    volumes:
      # You can replace /opt/data/mongo_home by any path to
      # a directory on your machine.
      # MongoDB will use that directory to store all the data.
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    image: lnquy/realize:2.0.2
    hostname: ofriends-backend
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      # Add more environments here if you want to pass it
      # to backend service env config.
      - DB_TYPE=mongodb
      - MONGODB_ADDRS=mongodb:27017
      #Ldap information include user first binding and basedn
      # change basedn to fit with manager OU
      - LDAP_ADDR=***REMOVED***
      - LDAP_PORT=389
      # change your ldap passowrd here
      # change your username in LDAP_FIRST_BIND_USERNAME=CN=yourusernmahere,OU=Admin_Privileges,OU=Revoke,DC=tma,DC=com,DC=vn
      - LDAP_FIRST_BIND_USERNAME=CN=,OU=Admin_Privileges,OU=Revoke,DC=tma,DC=com,DC=vn
      - LDAP_FIRST_BIND_PASSWORD=
      # BaseDN of TMALDAP, you when deploy this DN much change to TMAmanager
      - BASEDN=ou=TMAuser,dc=tma,dc=com,dc=vn
      # JWT information include private key and token time out :fomat h:m:s
      - PRIVATE_KEY=AllYourBase
      - TIME_OUT=1:30:00
    command: [ "start" ]
    volumes:
      # Add Go packages here if needed.
      - ../../.realize.yaml:/go/src/github.com/TheFlies/ofriends/.realize.yaml
      - ../../main.go:/go/src/github.com/TheFlies/ofriends/main.go
      - ../../internal:/go/src/github.com/TheFlies/ofriends/internal/
      - ../../vendor:/go/src/github.com/TheFlies/ofriends/vendor/
    working_dir: /go/src/github.com/TheFlies/ofriends
    depends_on:
      - mongodb
    restart: always

  frontend:
    image: node:11.10.0-alpine
    hostname: ofriend-frontend
    ports:
      - "8081:8081"
    environment:
      - OFRIENDS_BACKEND_ADDRS=http://backend:8080
    volumes:
      - ../../web:/home/ofriends
    working_dir: /home/ofriends/
    command: [ sh, -c, "npm rebuild node-sass && npm run serve" ]
    depends_on:
      - backend
    restart: always
